// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pconrumpggqvpanbzgju.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBjb25ydW1wZ2dxdnBhbmJ6Z2p1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk1NTE2OTAsImV4cCI6MjA3NTEyNzY5MH0.T67u5bCsg-qhWDXLNeRSxODOI0jXuoGGP1lSV6d_0PU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});